### ISSUE TITLE
GELF input doesnt reach elasticsearch output, but stdout output.

### ISSUE THREAD

**Issue by simonjohansson** [elasticsearch/logstash#1306] opened 2014-04-28 16:39 UTC
Hello.
ES 1.1.1
Logstash 1.4

Im running logstash like so,
```
./bin/logstash --debug -v -e ' input { tcp { port => 5141 } gelf { } } output { stdout { } elasticsearch_http { host => "es-host" } }'
```

Im sending a tcp package like so,

```
$ echo "Hello, Im from nc" | nc localhost 5141
```

And a GELF message like so

```
gelf = GELF::Notifier.new("logstash-host", 12201, "WAN", { :facility => "appname" })
gelf.notify! "Hello, im a gelf message"
```

The logstash spits out the following on stdout 

```
Compiled pipeline code:
@inputs = []
@filters = []
@outputs = []
@input_tcp_1 = plugin("input", "tcp", LogStash::Util.hash_merge_many({ "port" => 5141 }))

@inputs << @input_tcp_1
@input_gelf_2 = plugin("input", "gelf")

@inputs << @input_gelf_2
@output_stdout_3 = plugin("output", "stdout")

@outputs << @output_stdout_3
@output_elasticsearch_http_4 = plugin("output", "elasticsearch_http", LogStash::Util.hash_merge_many({ "host" => ("spr-prod-dogo-es-01.my-domain.com".force_encoding("UTF-8")) }))

@outputs << @output_elasticsearch_http_4
  @filter_func = lambda do |event, &block|
    extra_events = []
    @logger.debug? && @logger.debug("filter received", :event => event.to_hash)
    extra_events.each(&block)
  end
  @output_func = lambda do |event, &block|
    @logger.debug? && @logger.debug("output received", :event => event.to_hash)
    @output_stdout_3.handle(event)
    @output_elasticsearch_http_4.handle(event)
    
  end {:level=>:debug, :file=>"logstash/pipeline.rb", :line=>"26"}
Using milestone 2 input plugin 'tcp'. This plugin should be stable, but if you see strange behavior, please let us know! For more information on plugin milestones, see http://logstash.net/docs/1.4.0/plugin-milestones {:level=>:warn, :file=>"logstash/config/mixin.rb", :line=>"209"}
config LogStash::Codecs::Line/@charset = "UTF-8" {:level=>:debug, :file=>"logstash/config/mixin.rb", :line=>"105"}
config LogStash::Inputs::Tcp/@port = 5141 {:level=>:debug, :file=>"logstash/config/mixin.rb", :line=>"105"}
config LogStash::Inputs::Tcp/@debug = false {:level=>:debug, :file=>"logstash/config/mixin.rb", :line=>"105"}
config LogStash::Inputs::Tcp/@codec = <LogStash::Codecs::Line charset=>"UTF-8"> {:level=>:debug, :file=>"logstash/config/mixin.rb", :line=>"105"}
config LogStash::Inputs::Tcp/@add_field = {} {:level=>:debug, :file=>"logstash/config/mixin.rb", :line=>"105"}
config LogStash::Inputs::Tcp/@host = "0.0.0.0" {:level=>:debug, :file=>"logstash/config/mixin.rb", :line=>"105"}
config LogStash::Inputs::Tcp/@data_timeout = -1 {:level=>:debug, :file=>"logstash/config/mixin.rb", :line=>"105"}
config LogStash::Inputs::Tcp/@mode = "server" {:level=>:debug, :file=>"logstash/config/mixin.rb", :line=>"105"}
config LogStash::Inputs::Tcp/@ssl_enable = false {:level=>:debug, :file=>"logstash/config/mixin.rb", :line=>"105"}
config LogStash::Inputs::Tcp/@ssl_verify = false {:level=>:debug, :file=>"logstash/config/mixin.rb", :line=>"105"}
config LogStash::Inputs::Tcp/@ssl_key_passphrase = <password> {:level=>:debug, :file=>"logstash/config/mixin.rb", :line=>"105"}
Using milestone 2 input plugin 'gelf'. This plugin should be stable, but if you see strange behavior, please let us know! For more information on plugin milestones, see http://logstash.net/docs/1.4.0/plugin-milestones {:level=>:warn, :file=>"logstash/config/mixin.rb", :line=>"209"}
config LogStash::Codecs::Plain/@charset = "UTF-8" {:level=>:debug, :file=>"logstash/config/mixin.rb", :line=>"105"}
config LogStash::Inputs::Gelf/@debug = false {:level=>:debug, :file=>"logstash/config/mixin.rb", :line=>"105"}
config LogStash::Inputs::Gelf/@codec = <LogStash::Codecs::Plain charset=>"UTF-8"> {:level=>:debug, :file=>"logstash/config/mixin.rb", :line=>"105"}
config LogStash::Inputs::Gelf/@add_field = {} {:level=>:debug, :file=>"logstash/config/mixin.rb", :line=>"105"}
config LogStash::Inputs::Gelf/@host = "0.0.0.0" {:level=>:debug, :file=>"logstash/config/mixin.rb", :line=>"105"}
config LogStash::Inputs::Gelf/@port = 12201 {:level=>:debug, :file=>"logstash/config/mixin.rb", :line=>"105"}
config LogStash::Inputs::Gelf/@remap = true {:level=>:debug, :file=>"logstash/config/mixin.rb", :line=>"105"}
config LogStash::Inputs::Gelf/@strip_leading_underscore = true {:level=>:debug, :file=>"logstash/config/mixin.rb", :line=>"105"}
config LogStash::Codecs::Line/@charset = "UTF-8" {:level=>:debug, :file=>"logstash/config/mixin.rb", :line=>"105"}
config LogStash::Outputs::Stdout/@type = "" {:level=>:debug, :file=>"logstash/config/mixin.rb", :line=>"105"}
config LogStash::Outputs::Stdout/@tags = [] {:level=>:debug, :file=>"logstash/config/mixin.rb", :line=>"105"}
config LogStash::Outputs::Stdout/@exclude_tags = [] {:level=>:debug, :file=>"logstash/config/mixin.rb", :line=>"105"}
config LogStash::Outputs::Stdout/@codec = <LogStash::Codecs::Line charset=>"UTF-8"> {:level=>:debug, :file=>"logstash/config/mixin.rb", :line=>"105"}
config LogStash::Outputs::Stdout/@workers = 1 {:level=>:debug, :file=>"logstash/config/mixin.rb", :line=>"105"}
Using milestone 2 output plugin 'elasticsearch_http'. This plugin should be stable, but if you see strange behavior, please let us know! For more information on plugin milestones, see http://logstash.net/docs/1.4.0/plugin-milestones {:level=>:warn, :file=>"logstash/config/mixin.rb", :line=>"209"}
config LogStash::Codecs::Plain/@charset = "UTF-8" {:level=>:debug, :file=>"logstash/config/mixin.rb", :line=>"105"}
config LogStash::Outputs::ElasticSearchHTTP/@host = "spr-prod-dogo-es-01.my-domain.com" {:level=>:debug, :file=>"logstash/config/mixin.rb", :line=>"105"}
config LogStash::Outputs::ElasticSearchHTTP/@type = "" {:level=>:debug, :file=>"logstash/config/mixin.rb", :line=>"105"}
config LogStash::Outputs::ElasticSearchHTTP/@tags = [] {:level=>:debug, :file=>"logstash/config/mixin.rb", :line=>"105"}
config LogStash::Outputs::ElasticSearchHTTP/@exclude_tags = [] {:level=>:debug, :file=>"logstash/config/mixin.rb", :line=>"105"}
config LogStash::Outputs::ElasticSearchHTTP/@codec = <LogStash::Codecs::Plain charset=>"UTF-8"> {:level=>:debug, :file=>"logstash/config/mixin.rb", :line=>"105"}
config LogStash::Outputs::ElasticSearchHTTP/@workers = 1 {:level=>:debug, :file=>"logstash/config/mixin.rb", :line=>"105"}
config LogStash::Outputs::ElasticSearchHTTP/@index = "logstash-%{+YYYY.MM.dd}" {:level=>:debug, :file=>"logstash/config/mixin.rb", :line=>"105"}
config LogStash::Outputs::ElasticSearchHTTP/@manage_template = true {:level=>:debug, :file=>"logstash/config/mixin.rb", :line=>"105"}
config LogStash::Outputs::ElasticSearchHTTP/@template_name = "logstash" {:level=>:debug, :file=>"logstash/config/mixin.rb", :line=>"105"}
config LogStash::Outputs::ElasticSearchHTTP/@template_overwrite = false {:level=>:debug, :file=>"logstash/config/mixin.rb", :line=>"105"}
config LogStash::Outputs::ElasticSearchHTTP/@port = 9200 {:level=>:debug, :file=>"logstash/config/mixin.rb", :line=>"105"}
config LogStash::Outputs::ElasticSearchHTTP/@user = nil {:level=>:debug, :file=>"logstash/config/mixin.rb", :line=>"105"}
config LogStash::Outputs::ElasticSearchHTTP/@password = <password> {:level=>:debug, :file=>"logstash/config/mixin.rb", :line=>"105"}
config LogStash::Outputs::ElasticSearchHTTP/@flush_size = 100 {:level=>:debug, :file=>"logstash/config/mixin.rb", :line=>"105"}
config LogStash::Outputs::ElasticSearchHTTP/@idle_flush_time = 1 {:level=>:debug, :file=>"logstash/config/mixin.rb", :line=>"105"}
config LogStash::Outputs::ElasticSearchHTTP/@document_id = nil {:level=>:debug, :file=>"logstash/config/mixin.rb", :line=>"105"}
config LogStash::Outputs::ElasticSearchHTTP/@replication = "sync" {:level=>:debug, :file=>"logstash/config/mixin.rb", :line=>"105"}
Starting tcp input listener {:address=>"0.0.0.0:5141", :level=>:info, :file=>"logstash/inputs/tcp.rb", :line=>"84"}
Pipeline started {:level=>:info, :file=>"logstash/pipeline.rb", :line=>"78"}
Starting gelf listener {:address=>"0.0.0.0:12201", :level=>:info, :file=>"logstash/inputs/gelf.rb", :line=>"70"}
Automatic template management enabled {:manage_template=>"true", :level=>:info, :file=>"logstash/outputs/elasticsearch_http.rb", :line=>"104"}
Template Search URL: {:template_search_url=>"http://spr-prod-dogo-es-01.my-domain.com:9200/_template/*", :level=>:debug, :file=>"logstash/outputs/elasticsearch_http.rb", :line=>"112"}
Accepted connection {:client=>"127.0.0.1:41478", :server=>"0.0.0.0:5141", :level=>:debug, :file=>"logstash/inputs/tcp.rb", :line=>"165"}
config LogStash::Codecs::Line/@charset = "UTF-8" {:level=>:debug, :file=>"logstash/config/mixin.rb", :line=>"105"}
output received {:event=>{"message"=>"Hello, Im from nc", "@version"=>"1", "@timestamp"=>"2014-04-28T16:34:26.176Z", "host"=>"127.0.0.1:41478"}, :level=>:debug, :file=>"(eval)", :line=>"22"}
Connection closed {:client=>"127.0.0.1:41478", :level=>:debug, :file=>"logstash/inputs/tcp.rb", :line=>"120"}
2014-04-28T16:34:26.176+0000 127.0.0.1:41478 Hello, Im from nc
Flushing output {:outgoing_count=>1, :time_since_last_flush=>7.522, :outgoing_events=>{nil=>[[#<LogStash::Event:0xc2be308 @accessors=#<LogStash::Util::Accessors:0x15462876 @store={"message"=>"Hello, Im from nc", "@version"=>"1", "@timestamp"=>"2014-04-28T16:34:26.176Z", "host"=>"127.0.0.1:41478"}, @lut={"host"=>[{"message"=>"Hello, Im from nc", "@version"=>"1", "@timestamp"=>"2014-04-28T16:34:26.176Z", "host"=>"127.0.0.1:41478"}, "host"], "message"=>[{"message"=>"Hello, Im from nc", "@version"=>"1", "@timestamp"=>"2014-04-28T16:34:26.176Z", "host"=>"127.0.0.1:41478"}, "message"]}>, @data={"message"=>"Hello, Im from nc", "@version"=>"1", "@timestamp"=>"2014-04-28T16:34:26.176Z", "host"=>"127.0.0.1:41478"}, @cancelled=false>, "logstash-%{+YYYY.MM.dd}", ""]]}, :batch_timeout=>1, :force=>nil, :final=>nil, :level=>:debug, :file=>"stud/buffer.rb", :line=>"207"}
output received {:event=>{"facility"=>"appname", "version"=>"1.0", "host"=>"lagbchch00-0016.my-domain.com", "level"=>6, "file"=>"(irb)", "line"=>57, "@version"=>"1", "@timestamp"=>"2014-04-28T16:34:29.164Z", "source_host"=>"10.0.14.26", "message"=>"Hello, Im a gelf message"}, :level=>:debug, :file=>"(eval)", :line=>"22"}
2014-04-28T16:34:29.164+0000 lagbchch00-0016 Hello, Im a gelf message
Flushing output {:outgoing_count=>1, :time_since_last_flush=>2.851, :outgoing_events=>{nil=>[[#<LogStash::Event:0x38f28473 @accessors=#<LogStash::Util::Accessors:0x39d5b73a @store={"facility"=>"appname", "version"=>"1.0", "host"=>"lagbchch00-0016.my-domain.com", "level"=>6, "file"=>"(irb)", "line"=>57, "@version"=>"1", "@timestamp"=>"2014-04-28T16:34:29.164Z", "source_host"=>"10.0.14.26", "message"=>"Hello, Im a gelf message"}, @lut={"source_host"=>[{"facility"=>"appname", "version"=>"1.0", "host"=>"lagbchch00-0016.my-domain.com", "level"=>6, "file"=>"(irb)", "line"=>57, "@version"=>"1", "@timestamp"=>"2014-04-28T16:34:29.164Z", "source_host"=>"10.0.14.26", "message"=>"Hello, Im a gelf message"}, "source_host"], "timestamp"=>[{"facility"=>"appname", "version"=>"1.0", "host"=>"lagbchch00-0016.my-domain.com", "level"=>6, "file"=>"(irb)", "line"=>57, "@version"=>"1", "@timestamp"=>"2014-04-28T16:34:29.164Z", "source_host"=>"10.0.14.26", "message"=>"Hello, Im a gelf message"}, "timestamp"], "@timestamp"=>[{"facility"=>"appname", "version"=>"1.0", "host"=>"lagbchch00-0016.my-domain.com", "level"=>6, "file"=>"(irb)", "line"=>57, "@version"=>"1", "@timestamp"=>"2014-04-28T16:34:29.164Z", "source_host"=>"10.0.14.26", "message"=>"Hello, Im a gelf message"}, "@timestamp"], "full_message"=>[{"facility"=>"appname", "version"=>"1.0", "host"=>"lagbchch00-0016.my-domain.com", "level"=>6, "file"=>"(irb)", "line"=>57, "@version"=>"1", "@timestamp"=>"2014-04-28T16:34:29.164Z", "source_host"=>"10.0.14.26", "message"=>"Hello, Im a gelf message"}, "full_message"], "short_message"=>[{"facility"=>"appname", "version"=>"1.0", "host"=>"lagbchch00-0016.my-domain.com", "level"=>6, "file"=>"(irb)", "line"=>57, "@version"=>"1", "@timestamp"=>"2014-04-28T16:34:29.164Z", "source_host"=>"10.0.14.26", "message"=>"Hello, Im a gelf message"}, "short_message"], "message"=>[{"facility"=>"appname", "version"=>"1.0", "host"=>"lagbchch00-0016.my-domain.com", "level"=>6, "file"=>"(irb)", "line"=>57, "@version"=>"1", "@timestamp"=>"2014-04-28T16:34:29.164Z", "source_host"=>"10.0.14.26", "message"=>"Hello, Im a gelf message"}, "message"], "host"=>[{"facility"=>"appname", "version"=>"1.0", "host"=>"lagbchch00-0016.my-domain.com", "level"=>6, "file"=>"(irb)", "line"=>57, "@version"=>"1", "@timestamp"=>"2014-04-28T16:34:29.164Z", "source_host"=>"10.0.14.26", "message"=>"Hello, Im a gelf message"}, "host"]}>, @data={"facility"=>"appname", "version"=>"1.0", "host"=>"lagbchch00-0016.my-domain.com", "level"=>6, "file"=>"(irb)", "line"=>57, "@version"=>"1", "@timestamp"=>"2014-04-28T16:34:29.164Z", "source_host"=>"10.0.14.26", "message"=>"Hello, Im a gelf message"}, @cancelled=false>, "logstash-%{+YYYY.MM.dd}", ""]]}, :batch_timeout=>1, :force=>nil, :final=>nil, :level=>:debug, :file=>"stud/buffer.rb", :line=>"207"}

```

In kibana I can see the netcat message but not the GELF one, ES logs doesnt say anything either.

Any ideas?

Thanks!
Simon.

**Comment by jordansissel** [comment] 2015-01-23 19:40
I tested this with the reproduction example above with small modification to the logstash config (elasticsearch_http is deprecated. I used elasticsearch instead)

```
% curl -s 'localhost:9200/logstash-*/_search?q=*&pretty' | egrep '{|hits|source'
{
  "_shards" : {
  "hits" : {
    "hits" : [ {
      "_source":{"message":"Hello, Im from nc","@version":"1","@timestamp":"2015-01-23T19:36:01.157Z","host":"127.0.0.1"}
    }, {
      "_source":{"facility":"appname","version":"1.0","host":"Macintosh.local","level":6,"file":"(irb)","line":5,"@version":"1","@timestamp":"2015-01-23T19:36:22.247Z","source_host":"127.0.0.1","message":"Hello, im a gelf message"}
    }, {
      "_source":{"message":"Hello, Im from nc","@version":"1","@timestamp":"2015-01-23T19:36:04.694Z","host":"127.0.0.1"}
```

THis works for me.

**Comment by jordansissel** [comment] 2015-01-23 19:40
^^ I sent 2 tcp messages w/ netcat, and 1 with gelf. Both went through to ES

**Comment by jordansissel** [comment] 2015-01-23 19:41
This config worked for me:
```
% ./bin/logstash --debug -v -e ' input { tcp { port => 5141 } gelf { } } output { stdout { } elasticsearch{ protocol => http host => "localhost" } }'

```

Closing. Reopen if this is still a problem for you.

**Closed by jordansissel** 2015-01-23 19:41 UTC

**Comment by simonjohansson** [comment] 2015-02-03 09:43
Totally forgot about this issues, I have since switched from elasticsearch_http :)
Thanks.
