### ISSUE TITLE
Issue using metric filter with if conditionals 

### ISSUE THREAD

**Issue by shankarramshivram** [elasticsearch/logstash#2576] opened 2015-02-10 23:24 UTC
Using Logstash version :- 1.4.2 
The problem i am seeing is when i am trying to use the metric filter inside  conditional if loop,
logstash doesnt seem to apply the metric filter .

However if there is no if loop and i use the metric filter directly logstash recognises the filter.

My sample configs are as follows :-

 config -Not working  [ grok and date filter are matched and i can see the changes but not metric filter]
filter {
    if [type] == "catalog_logs" {
        grok {
            match => { "message" => XXXXXX(ghas response as a field" }
        }
        metrics {
           meter => [ "http_shankcatalog.%{response}"]
           add_tag => [ "metric" ]
           }
        date {
            match => [ "time", "MM/d/yy HH:mm:ss:SSS"]
            target => ["@timestamp"]
            }
    }
}

Working config 
filter {
    grok {
        match => { "message" => XXXXXX(has response as a field" }
        }
    metrics {
       meter => [ "http_catalog_shanklatest.%{response}"]
       add_tag => [ "metric" ]
     }
    date {
        match => [ "time", "MM/d/yy HH:mm:ss:SSS"]
        target => ["@timestamp"]
     }
}

**Comment by suyograo** [comment] 2015-02-10 23:27
Hi this was fixed in 1.5

Filters that generated events (multiline, clone, split, metrics) now propagate those events correctly to future conditionals (#1431)

**Comment by shankarramshivram** [comment] 2015-02-10 23:29
Hi Thanks for this... just saw the fix ... trying out 1.5 now..

**Comment by shankarramshivram** [comment] 2015-02-11 00:22
@suyograo  :- I just tried using 1.5beta1  but still see the same issue..

**Comment by suyograo** [comment] 2015-02-11 00:33
@shankarramshivram thanks for the feedback, we will reproduce

**Comment by wiibaa** [comment] 2015-02-11 05:54
@suyograo I suppose 1.5.0beta1 package does not contains https://github.com/logstash-plugins/logstash-filter-metrics/pull/5

@shankarramshivram can you confirm the plugin version is 0.1.3 by running `bin\logstash plugin list logstash-filter-metrics` Then you can update it by running `bin\logstash plugin update logstash-filter-metrics`

**Comment by shankarramshivram** [comment] 2015-02-13 01:04
@wiibaa  lemme try this ... will update..

**Comment by shankarshivram** [comment] 2015-02-13 21:45
@wiibaa  - Yep u were right-- the initial plugin version was 0.1.3.. i ran the update and now its 0.1.5.. Checking if the issue is fixed... after this..

Will update

**Comment by jsvd** [comment] 2015-02-26 16:34
@shankarramshivram has 0.1.5 fixed it for you?

**Comment by jsvd** [comment] 2015-03-09 20:42
This is fixed on 1.5.0rc2, closing

**Closed by jsvd** 2015-03-09 20:42 UTC
Labels: bug, needs more info
