### ISSUE TITLE
Logstash date filter is adding +5h to actual log time

### ISSUE THREAD

**Issue by Kashlikov** [elasticsearch/logstash#2722] opened 2015-02-28 22:37 UTC
Hi, I have such problem.  

I'm located in US and installed ELK stack for log analysis.  Issue is that when I'm parsing log, in which time is EST, but in logstash output it is shown with +5hours.  Example is below:

"message" => "27 Feb 2015 13:36:23,135 |  | WARN  | 1871890278-16711 | log                              | 77 - org.eclipse.jetty.util - 7.4.5.fuse20111017 | SSL renegotiate denied: java.nio.channels.SocketChannel[connected oshut local=/148.112.54.79:8443 remote=/148.112.156.70:35956]",
"@version" => "1",
"@timestamp" => "2015-02-27T18:36:23.135Z",

I have tried adding timezone to filter, but it doesn't help. 

Here is my date filter

date {
       match => ["logdate", "dd MMM yyyy HH:mm:ss,SSS"]
       timezone => "America/New_York" 
    }

**Comment by untergeek** [comment] 2015-02-28 23:42
I'm sorry that you've been experiencing confusion.  Thanks for taking the time to submit an issue to us.  Fortunately, the behavior you've observed and described is exactly how Logstash is supposed to operate.

Elasticsearch prefers time to be in UTC.  In fact, internal to Lucene (the search library powering Elasticsearch), the date is stored as epoch time + milliseconds, even though the `@timestamp` field still shows as human readable.  The reason for Elasticsearch having this behavior is that calculating date ranges is remarkably easy when just comparing big integers.

Because of this, and because Kibana also auto-corrects from UTC to your local time, Logstash always converts from whatever local time is being used to UTC.  The output is in ISO8601 with what's known as Zulu notation (See: http://en.wikipedia.org/wiki/ISO_8601#UTC), hence the 'Z' at the end of the time string.

If no timezone is configured in the date filter, Logstash will automatically use its server's configured timezone.  That's why even when you specified "America/New_York" it didn't change the outcome.  If you'd picked something in another time zone, you would have seen the resulting (but miscalculated) UTC time change.

As the behavior described is the expected behavior, I am closing this ticket.

If you have issues with the date filter in the future, please submit issues to https://github.com/logstash-plugins/logstash-filter/date

Also, please see the [date filter documentation](http://www.elasticsearch.org/guide/en/logstash/current/plugins-filters-date.html)

**Closed by untergeek** 2015-02-28 23:42 UTC
