### ISSUE TITLE
Lumberjack input plugin does not seem to honor the `host` setting

### ISSUE THREAD

**Issue by smitelli** [elasticsearch/logstash#2417] opened 2015-01-23 20:34 UTC
I'm running logstash-1.4.2-1_2c0f5a1.noarch from the Elasticsearch repo on CentOS 6.6. Using the following input config...

    input {
      lumberjack {
        host => "10.0.4.144"
        port => 5627
        ssl_certificate => "..."
        ssl_key => "..."
        type => "lumberjack"
      }
    }

...I see the following in the verbose log...

    Starting lumberjack input listener {:address=>"10.0.4.144:5627", :level=>:info}

... and I would expect that the service would only be listening on the private interface that was specified. However, according to `netstat -an`...

    Active Internet connections (servers and established)
    Proto Recv-Q Send-Q Local Address               Foreign Address             State      
    ...
    tcp        0      0 :::5627                     :::*                        LISTEN
    ...

... and the service is listening on all interfaces, including the public IP address, which is not desired. Could this be a misconfiguration on my part?

**Comment by ph** [comment] 2015-01-26 14:58
No your configuration is right, there is a bug inside the `lumberjack` library we are using.
I'll close this one since the issue is already reported in https://github.com/elasticsearch/logstash-forwarder/issues/326

**Closed by ph** 2015-01-26 14:58 UTC
