### ISSUE TITLE
bin/logstash rspec does not work without adding development dependencies

### ISSUE THREAD

**Issue by purbon** [elasticsearch/logstash#2749] opened 2015-03-03 14:23 UTC
In logstash 1.4.2 user was able to run ```bin/logstash rspec``` without running any other command. But in logstash 1.5.x end user need to add development dependencies to run that command.

If you're into logstash 1.5.x and aim to run the test, you should keep in mind to run the ```bin/plugin install --development``` before you can run the tests. Logstash should inform the user properly then trying to run the tests without having the dependencies, or might be throw the readme.

**Comment by suyograo** [comment] 2015-03-05 07:41
Can we add this to the README

**Comment by purbon** [comment] 2015-03-05 11:01
@suyograo done in #2775

**Comment by ph** [comment] 2015-03-09 20:47
closing this one the actual ticket to fix the problem is https://github.com/elasticsearch/logstash/issues/2631

**Closed by ph** 2015-03-09 20:47 UTC
Labels: 1.5.0, doc, enhancement
