### ISSUE TITLE
Issues with Getting Started on windows

### ISSUE THREAD

**Issue by 16bytes** [elasticsearch/logstash#1426] opened 2014-06-06 16:25 UTC
I was challenged by @jordansissel via [twitter](https://twitter.com/jordansissel/status/474925576805830656) to outline my experiences setting up LogStash.  He asked me to create an issue.

First off, I suspect that most of my problems come from using Windows.  I was following [directions](http://logstash.net/docs/1.4.1/tutorials/getting-started-with-logstash):

    > cd logstash-1.4.1
    > bin/logstash -e 'input { stdin { } } output { stdout {} }' 
    No such command "-e"
    Usage: logstash <command> [command args]
    Run a command with the --help flag to see the arguments.
    For example: logstash agent --help
    
    Available commands:
      agent - runs the logstash agent
      version - emits version info about this logstash
      web - runs the logstash web ui (called Kibana)
      rspec - runs tests

Ok, no problem, I think "agent" is what I want:

    > bin/logstash agent -e 'input { stdin { } } output { stdout {} }' 
    No such command "{"

Hmm... maybe there are quoting problems with windows.  Let's see if there is a way to pass the config via file:

    > echo input { stdin { } } output { stdout {} } > config.txt
    > bin/logstash agent -f config.txt
    
Well, there's no output, but the getting started tells me I can type into stdout and see messages.  Cool.  But, what about this Kibana thing?  I can do logstash.bat web, but it doesn't tell me what port it's running on.  

I receive a suggestion that there's a [one liner](https://twitter.com/jordansissel/status/474941174634283008) to start everything!  Cool:

    > bin\logstash agent -e 'output { elasticsearch { embedded => true } }' -- web
    RubyIO.java:1468:in `fwrite': java.lang.NullPointerException
        from RubyIO.java:1408:in `write'
        from RubyIO$INVOKER$i$1$0$write.gen:-1:in `call'
        from RubyClass.java:690:in `finvoke'
        from Helpers.java:502:in `invoke'
        from RubyBasicObject.java:363:in `callMethod'
        from RubyIO.java:2486:in `write'
        from RubyIO.java:2474:in `putsSingle'
        from RubyIO.java:2403:in `puts1'
        from RubyIO.java:2376:in `puts'
        from RubyIO$INVOKER$i$puts.gen:-1:in `call'
        from CachingCallSite.java:326:in `cacheAndCall'
        from CachingCallSite.java:170:in `call'

Doh.  I try all of the above steps with cygwin, and don't have any more luck.

**Comment by peterskim12** [comment] 2015-02-11 21:15
Ran into the same issue but I actually got Logstash to run without the 'fwrite' exception when I ran it from Cygwin:
```
cat logs | /cygdrive/c/work/logstash-1.4.2/bin/logstash.bat agent -f logstash/complete.conf
```

**Comment by ph** [comment] 2015-02-23 21:16
thank you @16bytes for this report.

With the latest version from the master branch on Windows 2008, java version "1.7.0_75" and running under administrator

### test were made without cygwin:

```
PS C:\Users\Administrator\logstash> .\bin\logstash -e 'input { stdin { } } output { stdout {} }'
Logstash startup completed
Hello
2015-02-23T20:16:13.705Z WIN-ISP0U0D3N02 Hello

```

```
PS C:\Users\Administrator\logstash> .\bin\logstash agent -e 'input { stdin { } } output { stdout {} }'
Logstash startup completed
Hello
2015-02-23T20:17:07.728Z WIN-ISP0U0D3N02 Hello
```

Next tests require #2504 to be fixed a PR
```
PS C:\Users\Administrator\logstash> bin\logstash -f .\test.conf
Logstash startup completed
Hello
2015-02-23T20:32:58.572Z WIN-ISP0U0D3N02 Hello
```

```
PS C:\Users\Administrator\logstash> bin\logstash agent -f .\test.conf
Logstash startup completed
hello
2015-02-23T20:34:39.224Z WIN-ISP0U0D3N02 hello
```

```
PS C:\Users\Administrator\logstash> cat .\somelogs | bin\logstash agent -f .\test.conf
2015-02-23T20:38:34.241Z WIN-ISP0U0D3N02 Some log
Logstash startup completed
Logstash shutdown completed
PS C:\Users\Administrator\logstash> cat .\somelogs | bin\logstash -f .\test.conf
```

Concerning kibana, since K4 is now using a nodejs server for the backend
we have removed the logstash web command in commit https://github.com/elasticsearch/logstash/commit/3986158baccbbc61b0aa3a06758777e912235d01

**Comment by ph** [comment] 2015-02-23 21:22
This command work on windows from a master build.

```
PS C:\logstash-2.0.0.dev> bin\logstash agent -e 'input { stdin {}} output { elasticsearch { embedded => true } }'
Feb 23, 2015 9:18:49 PM org.elasticsearch.node.internal.InternalNode <init>
INFO: [Super Sabre] version[1.4.0], pid[2392], build[bc94bd8/2014-11-05T14:26:12Z]
Feb 23, 2015 9:20:41 PM org.elasticsearch.node.internal.InternalNode <init>
INFO: [Super Sabre] initializing ...
Feb 23, 2015 9:20:41 PM org.elasticsearch.plugins.PluginsService <init>
INFO: [Super Sabre] loaded [cloud-aws], sites []

[...]
```

**Comment by ph** [comment] 2015-02-23 22:05
I did a few more tests and I cannot reproduce the `RubyIO.java` error in the latest version or 1.4.2, I had a few inline parsing errors in 1.4.2 but they all seem to be fixed in the master branch.

**Comment by spangul** [comment] 2015-02-23 22:06
Thanks Pier

**Closed** 2015-02-24 19:53 UTC
Labels: blocker, bug, confirmed, windows
