### ISSUE TITLE
logstash upstart generating too much logs

### ISSUE THREAD

**Issue by samueletonon** [elasticsearch/logstash#1598] opened 2014-08-05 13:57 UTC
it would be better to have 
**console none**
instead of 
**console log**
inside */etc/init/logstash.conf* so we have a silent start and avoid generating a lot of logs  inside /var/log/upstart/logstash.log

**Comment by untergeek** [comment] 2015-01-23 19:24
You're welcome to set this yourself, as desired.  Disabling logging is not necessarily good default behavior, especially for those just getting started.

There is still room for discussion on this, but I am closing it for now.  Feel free to reopen if you believe this needs more discussion.

**Closed by untergeek** 2015-01-23 19:24 UTC

**Comment by samueletonon** [comment] 2015-01-30 11:35
Yeah i setted this on my own :-) . i think we come from different philosophy: i expect configuration to be oriented to "production use" wether you expect them to help debug. not a big deal

**Comment by JPvRiel** [comment] 2015-02-27 10:28
Yeah, this very issue hit me hard. My PoCs server had /var/log/upstart/logstash.conf full mess of json output messages for every log event. A cut n paste from a digital ocean tutorial was the cause. This fix was to be sure you don'e have `stdout` as an output.

```
output {
  elasticsearch { 
    host => localhost 
    cluster => "espoc" 
    }
#  stdout { codec => rubydebug }
#  NB! don't output to stdout in production mode, else it fills up /var/log/upstart/logstash.log with each and every processing message
}
```

**Comment by nitingadekar** [comment] 2020-01-14 12:22
Thanks for the discussion, My /etc/init/logstash.conf didn't had console in it, but was generating 12G of log everyday. I just added console none and now it has stopped logging the logstash activities.
