### ISSUE TITLE
logstash hangs after "invalid byte sequence in UTF-8" "Exception in filterworker" gsub after urldecode

### ISSUE THREAD

**Issue by timbunce** [elasticsearch/logstash#1695] opened 2014-09-04 17:01 UTC
In the logs (with logstash 1.4.2 running with -v) I see
```
{:timestamp=>"2014-09-04T10:13:51.684000-0500", :message=>"Exception in filterworker", "exception"=>#<ArgumentError: invalid byte sequence in UTF-8>,
"backtrace"=>["org/jruby/RubyString.java:3078:in `gsub'",
"org/jruby/RubyString.java:3046:in `gsub'", "/home/tiger/trunk_1409040752/comp/support_logstash/logstash/lib/logstash/filters/mutate.rb:315:in `gsub'", "org/jruby/RubyArray.java:1613:in `each'",
"/home/tiger/trunk_1409040752/comp/support_logstash/logstash/lib/logstash/filters/mutate.rb:294:in `gsub'",
"/home/tiger/trunk_1409040752/comp/support_logstash/logstash/lib/logstash/filters/mutate.rb:210:in `filter'", "(eval):921:in `initialize'", "org/jruby/RubyProc.java:271:in `call'",
"/home/tiger/trunk_1409040752/comp/support_logstash/logstash/lib/logstash/pipeline.rb:262:in `filter'",
"/home/tiger/trunk_1409040752/comp/support_logstash/logstash/lib/logstash/pipeline.rb:203:in `filterworker'",
"/home/tiger/trunk_1409040752/comp/support_logstash/logstash/lib/logstash/pipeline.rb:143:in `start_filters'"], :level=>:error}
```
followed by many many "Plugin is finished" log lines, including this one:
```
{:timestamp=>"2014-09-04T10:13:51.694000-0500", :message=>"Plugin is finished",
:plugin=><LogStash::Filters::Mutate gsub=>["message", "\\x1B\\[[0-9;]*[mK]", ""]>, :level=>:info}
```
which I guess is the cause of the exception. (That message came from a tcp input that has ``codec => line { charset => "UTF-8" }`` set. But that's another issue.)

And then nothing. Logstash has hung.

**Comment by timbunce** [comment] 2015-01-19 15:51
Any news? This got on the 1.4.3 milestone then removed and not added to the 1.5.0 milestone.

**Comment by jordansissel** [comment] 2015-01-19 18:46
@jlintz Can you be more specific?

**Comment by jordansissel** [comment] 2015-01-19 18:49
@timbunce I can confirm that I can reproduce:

---

```
% bin/logstash -e 'input { generator { message => "/a/sa/search?rgu=0;+%C3%BB%D3%D0%D5%D2%B5%BD=;+%B7%A2%CB%CD=" count => 1 } } filter { urldecode { } ruby { code => "require :pry.to_s; event.pry" } }'
[1] pry(#<LogStash::Event>)> self["message"].encoding
=> #<Encoding:UTF-8>
[2] pry(#<LogStash::Event>)> self["message"].valid_encoding?
=> false
```

**Comment by jordansissel** [comment] 2015-01-19 18:53
I don't know what the correct solution is, here. 
* Does the urldecode filter need a charset setting to allow users to hint what charset to decode the result as?
* Should we fudge any invalid things with LogStash::Util::Charset? (This is what plain/line codecs do today)

```
[9] pry(#<LogStash::Event>)> c = LogStash::Util::Charset.new("UTF-8")
[13] pry(#<LogStash::Event>)> puts c.convert(self["message"])
Received an event that has a different character encoding than you configured. {:text=>"/a/sa/search?rgu=0;+û\\xD3\\xD0\\xD5ҵ\\xBD=;+\\xB7\\xA2\\xCB\\xCD=", :expected_charset=>"UTF-8", :level=>:warn}
/a/sa/search?rgu=0;+û\xD3\xD0\xD5ҵ\xBD=;+\xB7\xA2\xCB\xCD=
```

**Comment by timbunce** [comment] 2015-01-19 20:40
* Please don't drop the event! (ever)
* Being consistent with what codecs do sounds best - you don't have to squint hard to see urldecode is a kind of codec.
* A charset setting would be handy but not essential (for me at least) given the above.

Note that handling of encoding issues is required for parameter _names_ as well as _values_.

I don't know what LogStash::Util::Charset does, but ideally it should retain enough information to reconstruct the original data if needed. Of the options presented in the [Invalid byte sequences](http://en.wikipedia.org/wiki/UTF-8#Invalid_byte_sequences) section of the Wikipedia UTF-8 page, I'd prefer this approach:
> The Unicode code points U+0080–U+00FF with the same value as the byte, thus interpreting the bytes according to ISO-8859-1

**Comment by jordansissel** [comment] 2015-01-19 20:44
> I don't know what LogStash::Util::Charset does

It turns invalid byte sequences into escapes. So an invalid 2-byte sequence 0xD3D0 would become, literally, '\xD3\xD0'. 8 Characters, the backslash and x are actually part of the string. This would allow you to later reconstruct somehow with code by turning the text "\xD3\xD0" (8 bytes) into the 2-byte sequence once again.

**Comment by jordansissel** [comment] 2015-01-19 20:45
@timbunce I am in favor of using the codec-charset-fudging with urldecode also.

**Comment by jlintz** [comment] 2015-01-20 15:20
@jordansissel we've been seeing

`{:timestamp=>"2015-01-20T08:21:17.636000-0500", :message=>"Exception in filterworker", "exception"=>#<ArgumentError: invalid byte sequence in UTF-8>, "backtrace"=>["org/jruby/RubyString.java:5127:in `scan'", "/opt/logstash/lib/logstash/filters/kv.rb:209:in `parse'", "/opt/logstash/lib/logstash/filters/kv.rb:175:in `filter'", "(eval):1141:in `initialize'", "org/jruby/RubyProc.java:271:in `call'", "/opt/logstash/lib/logstash/pipeline.rb:262:in `filter'", "/opt/logstash/lib/logstash/pipeline.rb:203:in `filterworker'", "/opt/logstash/lib/logstash/pipeline.rb:143:in `start_filters'"], :level=>:error}`

and then lockups.  We only use the `kv` filter for nginx logs, where we log in "JSON format", which Nginx can't enforce valid JSON since our logformat is just structuring things manually.  I wonder the occasionally improperly encoded JSON lines are causing issues, even though our input is using the JSON codec

**Comment by jordansissel** [comment] 2015-01-21 17:40
@jlintz can you show me your input configuration?

**Comment by jlintz** [comment] 2015-01-21 19:07
@jordansissel input is just
```
input {
    lumberjack {
      port               => 12345
      ssl_certificate    => "removed"
      ssl_key            => "removed"
      codec              => json
    }
}
```

**Comment by jordansissel** [comment] 2015-01-21 19:41
@jlintz I think your case is different. This ticket is about urldecode filter introducing invalid-encoded-text after decoding. Your bug is about lumberjack input, I guess, not correctly patching invalid JSON?

**Comment by jlintz** [comment] 2015-01-21 19:47
@jordansissel possibly? heh , the reason I added info was I'm seeing the error in the `kv` filter and we actually utilize the `urldecode` filter right before using the kv filter in a couple of places, mainly the spots where we get a high amount of events.  I haven't isolated it to which spot it's occurring yet.  But happy to open another issue if you think its completely different

**Comment by jordansissel** [comment] 2015-01-21 19:49
@jlintz I may have misunderstood -
 > We only use the kv filter

I read this to mean you only have the kv filter in use for this log type, which means urldecode filter is not used. Can you confirm by attaching your logstash config?

**Comment by jlintz** [comment] 2015-01-21 20:00
sure, sorry for the confusion.  Here is the logstash config for our processing of Nginx logs

```
filter {
    # Format Nginx Error logs
    if [type] =~ /nginx_.*_error/ {
        grok {
            match => {
                "message" => [
                    "%{DATESTAMP:timestamp} \[%{DATA:severity}\] (%{NUMBER:pid:int}#%{NUMBER}: \*%{NUMBER}|\*%{NUMBER}) %{GREEDYDATA:message}",
                    "%{DATESTAMP:timestamp} \[%{DATA:severity}\] %{GREEDYDATA:message}",
                    "%{DATESTAMP:timestamp} %{GREEDYDATA:message}"
                        ]
            }
            overwrite => [ "message" ]
        }

        grok {
            match =>  { "message" => [ "%{DATA:nginx_error}, %{GREEDYDATA:message}"] }
            overwrite => [ "message" ]
        }
        kv {
            field_split  => ","
            value_split  => ":"
            trimkey      => " "
            trim         => "\""
            exclude_keys => [ "host"]
        }
        mutate {
            strip => ["client", "server", "request", "upstream", "referrer"]
        }
        grok {
            match       => { "upstream" => [ "%{URIPROTO}://%{IPORHOST:upstream_ip}(?::%{POSINT:upstream_port})?%{URIPATH:upstream_request}%{URIPARAM:upstream_qs}" ] }
            remove_field => [ "message", "upstream", "port"]
        }


        if "/ping/ad" in [request] {
            mutate {
                add_tag => [ "ad_ping_drop" ]
            }
        }
        grok {
            match   => { "request" => [ "GET /ping/?(ad)?\?h=%{DATA:qs_host}&" ] }
        }

        if [upstream_ip] {
            cidr {
              add_tag => ["ec2_ip"]
              address => ["%{upstream_ip}"]
              network => [
                "10.0.0.0/8"
              ]
            }

            mutate {
                add_field => { "upstream_host" => "%{upstream_ip}" }
            }
            
            if "ec2_ip" in [tags] {
                dns {
                    reverse => ["upstream_host"]
                    action  => "replace"
                }
            }

            if [upstream_port] {
                mutate {
                    add_field => { "upstream_addr" => "%{upstream_host}:%{upstream_port}" }
                }
            } 
            else {
                mutate {
                    add_field => { "upstream_addr" => "%{upstream_host}" }
                }
            }
        }

        date {
            match => [ "timestamp", "yy/MM/dd HH:mm:ss" ]
            remove_field => [ "timestamp" ]
        }
    }
    # Handle Regular Nginx access logs
    else if [type] =~ /^nginx_/ {
        urldecode {
            field   => "query_strings"
        }
        kv {
            source       => "query_strings"
            prefix       => "qs_"
            field_split  => "&?"
            remove_field => [ "query_strings" ]
        }

        if [upstream_status] == "-" {
            mutate {
                remove_field => [ "upstream_status" ]
            }
        }

        if [upstream_response_time] == "-" {
            mutate {
                remove_field => [ "upstream_response_time" ]
            }
        }

        if [upstream_addr] and [upstream_addr] != "-" {
            mutate {
                split => [ "upstream_addr", ":" ]
            }

            cidr {
              add_tag => ["ec2_ip"]
              address => ["%{upstream_addr[0]}"]
              network => [
                "10.0.0.0/8"
              ]
            }

            mutate {
                add_field => [ "upstream_host" , "%{upstream_addr[0]}" ]
                add_field => [ "upstream_ip" , "%{upstream_addr[0]}" ]
                add_field => [ "upstream_port" , "%{upstream_addr[1]}" ]
            }

            mutate {
                remove_field => [ "upstream_addr" ]
            }

            if "ec2_ip" in [tags] {
                dns {
                    reverse => ["upstream_host"]
                    action  => "replace"
                }
            }
            mutate {
                add_field => { "upstream_addr" => "%{upstream_host}:%{upstream_port}" }
            }
        }

        cidr {
          add_tag => ["private_ip"]
          address => ["%{remote_addr}"]
          network => [
            "10.0.0.0/8",
            "127.0.0.0/8",
            "169.254.0.0/16",
            "172.16.0.0/12",
            "192.168.0.0/16"
          ]
        }

        # Only GeoIP on logs we care about
        if [type] in ["nginx_gator", "nginx_web"] {
            if "private_ip" not in [tags] {
                geoip {
                    fields   => [ "country_code2", "latitude", "longitude", "location", "region_name", "city_name" ]
                    source   => "remote_addr"
                    database => "/mnt/data/GeoIPCity.dat"
                }
            }
        }
    }
}
```


If you need the full config, I can probably post that as well.

**Comment by ph** [comment] 2015-01-21 20:30
@timbunce @jlintz I have created a PR in the urldecode plugin that should escape invalid utf-8 characters. https://github.com/logstash-plugins/logstash-filter-urldecode/pull/1

**Comment by ph** [comment] 2015-01-22 18:14
The fix was merged and will be a part of the Logstash 1.5 release

@jlintz If the new version of the `urldecode` plugin doesn't solve your issue feel free to open a new ticket.

**Closed by ph** 2015-01-22 18:14 UTC
Labels: adoptme, bug, confirmed

**Comment by timbunce** [comment] 2015-01-22 20:19
Thanks @ph!

**Comment by jonathanpmartins** [comment] 2016-06-02 03:04
hey @scakkia How can I solve the problem if logstash escape especial characteres?
My message is full with two backslahes: \\x22.
I live to remove only one backslash, and unpack the string with ruby. but logstash keeps escaping my one backlash, and so the result is nothing!

**Comment by AsyncTaskSola** [comment] 2023-03-27 03:08
I find if the path have Chinese it will be display this error ,so I change the path to English way ,then I can see the logstash can run right . Maybe u can change the way ,try again.
