### ISSUE TITLE
logstash 1.5 - multiline filter throws exception and logstash freezes

### ISSUE THREAD

**Issue by gillyb** [elasticsearch/logstash#2372] opened 2015-01-19 14:59 UTC
I am running a logstash1.5 node with a single thread. It receives via TCP input, parses the message according to syslog RFC5424 format, and it has a multiline filter on it.

The multiline filter is throwing this exception :
```
Exception in filterworker {"exception"=>#<NoMethodError: undefined method `|' for #<Java::JavaUtil::ArrayList:0x7a14b327>>, "backtrace"=>["/Users/gillyb/dev/gaia-hermes-logs-listener/dist/bin/logstash-1.5.0.beta1/lib/logstash/util.rb:41:in `hash_merge'", "org/jruby/RubyHash.java:1341:in `each'", "org/jruby/java/proxies/MapJavaProxy.java:414:in `each'", "/Users/gillyb/dev/gaia-hermes-logs-listener/dist/bin/logstash-1.5.0.beta1/lib/logstash/util.rb:33:in `hash_merge'", "/Users/gillyb/dev/gaia-hermes-logs-listener/dist/bin/logstash-1.5.0.beta1/lib/logstash/event.rb:185:in `append'", "/Users/gillyb/dev/gaia-hermes-logs-listener/dist/bin/logstash-1.5.0.beta1/vendor/bundle/jruby/1.9/gems/logstash-filter-multiline-0.1.2/lib/logstash/filters/multiline.rb:227:in `previous_filter!'", "/Users/gillyb/dev/gaia-hermes-logs-listener/dist/bin/logstash-1.5.0.beta1/vendor/bundle/jruby/1.9/gems/logstash-filter-multiline-0.1.2/lib/logstash/filters/multiline.rb:174:in `filter'", "(eval):101:in `initialize'", "org/jruby/RubyArray.java:1613:in `each'", "org/jruby/RubyEnumerable.java:805:in `flat_map'", "(eval):97:in `initialize'", "org/jruby/RubyProc.java:271:in `call'", "/Users/gillyb/dev/gaia-hermes-logs-listener/dist/bin/logstash-1.5.0.beta1/lib/logstash/pipeline.rb:268:in `filter'", "/Users/gillyb/dev/gaia-hermes-logs-listener/dist/bin/logstash-1.5.0.beta1/lib/logstash/pipeline.rb:206:in `filterworker'", "/Users/gillyb/dev/gaia-hermes-logs-listener/dist/bin/logstash-1.5.0.beta1/lib/logstash/pipeline.rb:150:in `start_filters'"], :level=>:error}
```

At this point the logstash freezes and stops processing incoming logs.

My configuration looks like this :
```
input {
  tcp {
    port => 4020
    codec => json
  }
}

filter {

  if [it] == "syslog" {
    grok {
      match => [ "message" , "%{SYSLOG5424BASE} +%{GREEDYDATA:message}"]
      overwrite => [ "message" ]
    }
  }
  multiline {
      pattern => "^>>.*"
      what => "previous"
    }
}

output {
  tcp {
    host => "localhost"
    port => 4000
    codec => json_lines
  }
}
```
(If i remove the grok parsing it still throws the same exception.)

Debugging the messages i'm sending, they all look correct.
Whenever I send a single line message it works great.
When I send multiline messages, each line after the first starts with ```>>``` (as you can see in the multiline pattern i defined).

**Comment by suyograo** [comment] 2015-01-19 15:57
@colinsurprenant since you are working through https://github.com/logstash-plugins/logstash-filter-multiline/pull/4, can you verify this?

**Comment by colinsurprenant** [comment] 2015-01-19 20:19
@gillyb ok, thanks for the report. I will investigate!

**Comment by colinsurprenant** [comment] 2015-01-19 20:55
@gillyb could you please share a sample input to reproduces with this config? 

With the multiline refactor I am about to merge this should be solved but I'd like to include a specific test for this case.

The problem you are seeing is related to the json parsing performance work we did in 1.5 and the `|` proxy method seems to be missing for Java collections.

**Comment by colinsurprenant** [comment] 2015-01-20 23:25
@gillyb I am unable to reproduce the problem locally. If you could send sample input to reproduce it would be really helpful and I'd like to include a spec for this. In the meantime I will go ahead a merge logstash-plugins/logstash-filter-multiline#4 - once the new plugin version is published you can also try it to see if it actually solve the issue.

**Comment by gillyb** [comment] 2015-01-21 08:15
@colinsurprenant Ok, I did some more thorough experimenting on my problem and realised that my problem is probably much more specific than I thought...

In my original scenario, I have a windows server, with some C# code, sending logs via log4net. This is sending logs in syslog RFC5424 format to a linux server.
On the linux server I have an agent that acts as a proxy - It checks for a token (some security precaution of mine) and passes the message on to my logstash node. This is where the multiline is configured, and the problem happened.

I stopped the messages in debug mode, just before they entered my logstash, copied the messages and tried to reproduce the scenario without the windows server, but couldn't.

When I run it from the windows server it happens everytime, so this leads me to believe that the problem is some kind of encoding issue, but I can't put my finger on it exactly.

I tried removing all '\r' characters which are specific to windows, but it still happens.

Do you have any ideas to what might be causing this ?

**Comment by colinsurprenant** [comment] 2015-01-21 19:16
I do have a good idea of the source of the problem and can see how it can happen but haven't bee able to reproduce :P 

The exception `undefined method | for #<Java::JavaUtil::ArrayList:0x7a14b327>>` happens because in 1.5 we switched to using JrJackson for Json parsing and one of the optimization is the use of native Java collections like `ArrayList`. In JRuby some Ruby Array methods are added to the Java `ArrayList` but not the union operator `|` which is used in the multiline filter. 

So this problem will/can happen only when the input data goes through the Json codec but when I last checked I couldn't craft the proper Json to reproduce.

I am not sure if encoding relates to this problem, maybe - it would have to trigger something with the Json parsing, not sure what/how. 

In any case, I am about to merge logstash-plugins/logstash-filter-multiline#4 which refactors this part of the code that does the array union and all arrays are now re-cast so this should not happen anymore. So basically, once I merge and publish the new multiline filter, you could check to see if it fixes the issue.

But, I'd still really like to find the proper input to reproduce this. Would it be possible for you to share the input that triggers that when sent from Windows?

**Comment by jordansissel** [comment] 2015-01-21 19:19
For a bit of humorous context, @colinsurprenant were talking about this bug on video, and as soon as we read the error message, both of us groaned - "Aghhhh JrJackson!!!!" hehe :)

**Comment by colinsurprenant** [comment] 2015-01-21 21:39
Ok, got it, I am able to reproduce. No need to provide sample input @gillyb

**Comment by gillyb** [comment] 2015-01-22 07:37
:+1:

**Comment by colinsurprenant** [comment] 2015-01-22 22:16
- Fixed by logstash-plugins/logstash-filter-multiline#4 published as https://rubygems.org/gems/logstash-filter-multiline version 0.1.4
- Added regression spec in logstash-plugins/logstash-filter-multiline#7

**Closed by colinsurprenant** 2015-01-22 22:16 UTC
Labels: bug
